name: Linting, Testing, Building
run-name: ${{ github.actor }} is learning GitHub Actions
# Shoul to "on"
# push:
#    branches: [main]
# pull_request:
#    branches: [main]
on: [push, pull_request]
jobs:
   pipeline:
      # runs-on: windows-2019
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [18.x]

      steps:
         - uses: actions/checkout@v2
         - name: Staring Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v1
           with:
              node-version: ${{ matrix.node-version }}

         - name: Install dependencies
           run: npm ci --force

         # - name: Prettier check
         #   run: npm run pret

         - name: Lint eslint
           run: npm run lint:ts
           if: always()

         - name: Lint stylelint
           run: npm run lint:style
           if: always()

         - name: Unit test
           run: npm run test:unit
           if: always()

         # - name: Build storybook
         #   run: npm run storybook:build
         #   if: always()
         # - name: UI test
         #   run: npm run test:ui:ci

         # - name: Create ui-report
         #   run: npm run test:ui:report

         - name: Build project
           run: npm run build:prod
           if: always()
         #   name: Install dependencies
         #   run: npm run
